server:
  port: 8089
  servlet:
    context-path: /api
jwt:
  lifetime: 10m
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/english-way?useSSL=false&serverTimezone=UTC
    username: root1
    password: root1
    driver-class-name: org.mariadb.jdbc.Driver
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:./users;MODE=PostgreSQL
#    url: jdbc:h2:mem:spring-security-sample
#    username: root
#    password: root
  jpa:
    show-sql: true
#    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: your-mailtrap-username
    password: your-mailtrap-password
#  main:
#    allow-circular-references: true

registration:
  activate:
    minute-expiration: 5
    url: /activate?code=
  change-password:
    url: /change?code=
frontend:
  url: http://localhost:4200
email:
  from: support@english-way.com
  email-dir: "c://temp//email"